// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1bQBpWlVL73gSqi2s8PfOKuhR4VrOs6w',
    appId: '1:1089393234039:web:bb7dee02904dedd65b3672',
    messagingSenderId: '1089393234039',
    projectId: 'test-login8',
    authDomain: 'test-login8.firebaseapp.com',
    storageBucket: 'test-login8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3a1pQ2gIyJYkVaI1NglPHVWsTyKRivm8',
    appId: '1:1089393234039:android:ae3e40ead2a541a35b3672',
    messagingSenderId: '1089393234039',
    projectId: 'test-login8',
    storageBucket: 'test-login8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFffrjxruOpvaPr8Vnope821pZSqtUZmQ',
    appId: '1:1089393234039:ios:50363c270bfa56dd5b3672',
    messagingSenderId: '1089393234039',
    projectId: 'test-login8',
    storageBucket: 'test-login8.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFffrjxruOpvaPr8Vnope821pZSqtUZmQ',
    appId: '1:1089393234039:ios:50363c270bfa56dd5b3672',
    messagingSenderId: '1089393234039',
    projectId: 'test-login8',
    storageBucket: 'test-login8.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1bQBpWlVL73gSqi2s8PfOKuhR4VrOs6w',
    appId: '1:1089393234039:web:d8a471e804a467ce5b3672',
    messagingSenderId: '1089393234039',
    projectId: 'test-login8',
    authDomain: 'test-login8.firebaseapp.com',
    storageBucket: 'test-login8.firebasestorage.app',
  );
}
